# Site settings
title: Tues, March 8th @ Stockholm City Conference Centre
email: johanna.westin@mtgx.se
url: http://techiewomen.org/
description: "Let's get more women involved in the technology and STEM jobs."
skills: "Join 6,000+ Intendees! Become One of the Thousands of Women Supporting, Mentoring and Promoting Diversity in Technology."
meta_author: Women in Technology 2016
name: Women in Technology 2016
# Google webmaster tools
google_verify: UA-72558635-1

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: WomenInTech

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 00baa0 #80B3FF #44AA99
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: WIT
  press: Press Inquiries
  social: Around the Web
  credits: Join our <a href='http://linkedin.com/groups/6627335'>WIT Global LinkedIn</a> and <a href='https://facebook.com/groups/WITGlobal/'>Facebook group</a> to stay up to date and begin to meet the inspiring community members.

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/#WIT2015
  - title: facebook
    url: https://www.facebook.com/groups/WITGlobal/
  - title: linkedin
    url: https://www.linkedin.com/groups/6627335/profile
  # - title: bitbucket
  #   url: http://bitbucket.org/jekyll
  # - title: github
  #   url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
press:
  - line: johanna.westin@mtgx.se
  - line: +46 73 699 18 17

# Credits content
credits: ''

# Build settings
markdown: kramdown
permalink: pretty
